### PR TITLE
Feature/concurrency_optimization

### PR DESCRIPTION
**Pull request by LorenzoTettamanti**
replaced threading with asyncio and aiohttp and aiofiles. Little code refactoring. created a printBanner function. Created parseArgs function

### CODE REVIEW

**Comment by girorme** [comment]
hi @LorenzoTettamanti nice pr!
Have you finished it? I can solve the conflicts

Have a nice day

**Comment by LorenzoTettamanti** [comment]
hey @girorme , thank you for the reply. Yeah i have finished. let me know if the code is running correctly

**Comment by LorenzoTettamanti** [comment]
@girorme If you have some implementation ideas i'll suggest you to open a public issue. I'll try to do that in my free time or maybe other developers can help you! 

Have a nice day!

**Comment by girorme** [comment]
@LorenzoTettamanti Perfect! I'm testing the pr. Nice ideia about public issues! 🚀

**Comment by girorme** [comment]
@LorenzoTettamanti merged! I've opened some issues to improve the tool

Thanks

**Comment by LorenzoTettamanti** [comment]
@girorme ok,i'll check!

**Pull request merged**
